import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import paymentsRouter from "./payments";
import settingsRouter from "./settings";
import chatbotRouter from "./chatbot";
import adminRouter from "./admin";
import widgetRouter from "./widget";
import analyticsRouter from "./analytics";
import broadcastRouter from "./broadcast";
import catalogRouter from "./catalog";
import flowsRouter from "./flows";
import servicesRouter from "./services";
import appointmentsRouter from "./appointments";
import remindersRouter from "./reminders";
import ordersRouter from "./orders";
import newsletterRouter from "./newsletter";
import afipRouter from "./afip";
import prospectorRouter from "./prospector";
import integrationsRouter from "./integrations";
import leadsRouter from "./leads";
import mcpRouter from "./mcp";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(paymentsRouter);
router.use(settingsRouter);
router.use(chatbotRouter);
router.use(adminRouter);
router.use(widgetRouter);
router.use(analyticsRouter);
router.use(broadcastRouter);
router.use(catalogRouter);
router.use(flowsRouter);
router.use(servicesRouter);
router.use(appointmentsRouter);
router.use(remindersRouter);
router.use(ordersRouter);
router.use(newsletterRouter);
router.use(afipRouter);
router.use(prospectorRouter);
router.use(integrationsRouter);
router.use(leadsRouter);
router.use(mcpRouter);

export default router;
